name: comp6011-task3
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - pillow
  - tqdm
  - matplotlib
  - pip
  - pip:
      - --index-url https://download.pytorch.org/whl/cu126
      - torch
      - torchvision 
      - torchaudio
      - xformers